# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment..
image: php:7.2-fpm

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - mv .env.example .env
          - apt-get update && apt-get install -y unzip
          - pecl install mongodb
          - docker-php-ext-enable mongodb
#          - docker-php-ext-install zip
#          - docker-php-ext-enable zip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
#          - mongo 127.0.0.1:27017/mongo_testing tests/init.js
          - vendor/bin/phpunit -c phpunit.xml
#          - npm install
        services: # Application services dependencies
          - mongo
          - mysql
#    - step:
#        # set HEROKU_API_KEY and HEROKU_APP_NAME environment variables
#        # set clone `depth: full' as described here: https://confluence.atlassian.com/x/Y9-5Mw
#        name: Deploy to Heroku
#        deployment: production   # set to test, staging or production
#        # trigger: manual  # uncomment to have a manual step
#        script:
#          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
definitions:
  services:
    mongo:
      image: mongo:3