<?php
use Carbon\Carbon;

$today =  Carbon::today()->toW3cString();
$check_at = Carbon::today()->addMonth()->toW3cString();

return [

    'identifications' => [
        ['code_afip' => '0', 'name' => 'CI Policía Federal'],
        ['code_afip' => '1', 'name' => 'CI Buenos Aires'],
        ['code_afip' => '2', 'name' => 'CI Catamarca'],
        ['code_afip' => '3', 'name' => 'CI Córdoba'],
        ['code_afip' => '4', 'name' => 'CI Corrientes'],
        ['code_afip' => '5', 'name' => 'CI Entre Ríos'],
        ['code_afip' => '6', 'name' => 'CI Jujuy'],
        ['code_afip' => '7', 'name' => 'CI Mendoza'],
        ['code_afip' => '8', 'name' => 'CI La Rioja'],
        ['code_afip' => '9', 'name' => 'CI Salta'],
        ['code_afip' => '10', 'name' => 'CI San Juan'],
        ['code_afip' => '11', 'name' => 'CI San Luis'],
        ['code_afip' => '12', 'name' => 'CI Santa Fe'],
        ['code_afip' => '13', 'name' => 'CI Santiago del Estero'],
        ['code_afip' => '14', 'name' => 'CI Tucumán'],
        ['code_afip' => '16', 'name' => 'CI Chaco'],
        ['code_afip' => '17', 'name' => 'CI Chubut'],
        ['code_afip' => '18', 'name' => 'CI Formosa'],
        ['code_afip' => '19', 'name' => 'CI Misiones'],
        ['code_afip' => '20', 'name' => 'CI Neuquén'],
        ['code_afip' => '21', 'name' => 'CI La Pampa'],
        ['code_afip' => '22', 'name' => 'CI Río Negro'],
        ['code_afip' => '23', 'name' => 'CI Santa Cruz'],
        ['code_afip' => '24', 'name' => 'CI Tierra del Fuego'],
        ['code_afip' => '80', 'name' => 'CUIT'],
        ['code_afip' => '86', 'name' => 'CUIL'],
        ['code_afip' => '87', 'name' => 'CDI'],
        ['code_afip' => '89', 'name' => 'LE'],
        ['code_afip' => '90', 'name' => 'LC'],
        ['code_afip' => '91', 'name' => 'CI extranjera'],
        ['code_afip' => '92', 'name' => 'en trámite'],
        ['code_afip' => '93', 'name' => 'Acta nacimiento'],
        ['code_afip' => '94', 'name' => 'Pasaporte'],
        ['code_afip' => '95', 'name' => 'CI Bs. As. RNP'],
        ['code_afip' => '96', 'name' => 'DNI'],
        ['code_afip' => '99', 'name' => 'Sin identificar/venta global diaria'],
        ['code_afip' => '30', 'name' => 'Certificado de Migración'],
        ['code_afip' => '88', 'name' => 'Usado por Anses para Padrón'],
    ],

    'options' => [
        ['key' => 'primary_color', 'default' => 'indigo', 'type' => 'params'],
        ['key' => 'accent_color', 'default' => 'pink', 'type' => 'params'],
        ['key' => 'subdist', 'default' => 'false', 'type' => 'params'],
        ['key' => 'seller', 'default' => 'false', 'type' => 'params'],
        ['key' => 'language', 'default' => 'es', 'type' => 'preferences'],
        ['key' => 'changeProductName', 'default' => 'all', 'type' => 'params'],
        ['key' => 'pricelist_supplier', 'default' => 'subdist', 'type' => 'params'],
        ['key' => 'pricelist_client', 'default' => 'subdist', 'type' => 'params'],
        ['key' => 'fiscal_printer', 'default' => 'true', 'type' => 'params'],
        ['key' => 'products_various_enabled', 'default' => 'false', 'type' => 'params'],
        ['key' => 'products_various_id', 'default' => '0', 'type' => 'params'],
        ['key' => 'final_consumer_id', 'default' => '0', 'type' => 'params'],
        ['key' => 'orders_company_header', 'default' => 'false', 'type' => 'params'],
    ],

    'receipts' => [
        ['code_afip' => '001', 'name' => 'FACTURAS A', 'receipt_type' => 'FACTURA', 'letter' => 'A'],
        ['code_afip' => '002', 'name' => 'NOTAS DE DEBITO A', 'receipt_type' => 'ND', 'letter' => 'A'],
        ['code_afip' => '003', 'name' => 'NOTAS DE CREDITO A', 'receipt_type' => 'NC', 'letter' => 'A'],
        ['code_afip' => '004', 'name' => 'RECIBOS A', 'receipt_type' => 'RECIBO', 'letter' => 'A'],
        ['code_afip' => '005', 'name' => 'NOTAS DE VENTA AL CONTADO A', 'receipt_type' => 'NV', 'letter' => 'A'],
        ['code_afip' => '006', 'name' => 'FACTURAS B', 'receipt_type' => 'FACTURA', 'letter' => 'B'],
        ['code_afip' => '007', 'name' => 'NOTAS DE DEBITO B', 'receipt_type' => 'ND', 'letter' => 'B'],
        ['code_afip' => '008', 'name' => 'NOTAS DE CREDITO B', 'receipt_type' => 'NC', 'letter' => 'B'],
        ['code_afip' => '009', 'name' => 'RECIBOS B', 'receipt_type' => 'RECIBO', 'letter' => 'B'],
        ['code_afip' => '010', 'name' => 'NOTAS DE VENTA AL CONTADO B', 'receipt_type' => 'NV', 'letter' => 'B'],
        ['code_afip' => '011', 'name' => 'FACTURAS C', 'receipt_type' => 'FACTURA', 'letter' => 'C'],
        ['code_afip' => '012', 'name' => 'NOTAS DE DEBITO C', 'receipt_type' => 'ND', 'letter' => 'C'],
        ['code_afip' => '013', 'name' => 'NOTAS DE CREDITO C', 'receipt_type' => 'NC', 'letter' => 'C'],
        ['code_afip' => '014', 'name' => 'DOCUMENTO ADUANERO', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '015', 'name' => 'RECIBOS C', 'receipt_type' => 'RECIBO', 'letter' => 'C'],
        ['code_afip' => '016', 'name' => 'NOTAS DE VENTA AL CONTADO C', 'receipt_type' => 'NV', 'letter' => 'C'],
        ['code_afip' => '019', 'name' => 'FACTURAS DE EXPORTACION', 'receipt_type' => 'FACTURA', 'letter' => ''],
        ['code_afip' => '020', 'name' => 'NOTAS DE DEBITO POR OPERACIONES CON EL EXTERIOR', 'receipt_type' => 'ND', 'letter' => ''],
        ['code_afip' => '021', 'name' => 'NOTAS DE CREDITO POR OPERACIONES CON EL EXTERIOR', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '022', 'name' => 'FACTURAS - PERMISO EXPORTACION SIMPLIFICADO - DTO. 855/97', 'receipt_type' => 'FACTURA', 'letter' => ''],
        ['code_afip' => '030', 'name' => 'COMPROBANTES DE COMPRA DE BIENES USADOS', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '031', 'name' => 'MANDATO - CONSIGNACION', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '032', 'name' => 'COMPROBANTES PARA RECICLAR MATERIALES', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '034', 'name' => 'COMPROBANTES A DEL APARTADO A  INCISO F  R G  N  1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'A'],
        ['code_afip' => '035', 'name' => 'COMPROBANTES B DEL ANEXO I, APARTADO A, INC. F), RG N° 1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'B'],
        ['code_afip' => '036', 'name' => 'COMPROBANTES C DEL Anexo I, Apartado A, INC.F), R.G. N° 1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'C'],
        ['code_afip' => '037', 'name' => 'NOTAS DE DEBITO O DOCUMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415', 'receipt_type' => 'ND', 'letter' => ''],
        ['code_afip' => '038', 'name' => 'NOTAS DE CREDITO O DOCMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '039', 'name' => 'OTROS COMPROBANTES A QUE CUMPLEN CON LA R G  1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'A'],
        ['code_afip' => '040', 'name' => 'OTROS COMPROBANTES B QUE CUMPLAN CON LA R.G. N° 1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'B'],
        ['code_afip' => '041', 'name' => 'OTROS COMPROBANTES C QUE CUMPLAN CON LA R.G. N° 1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'C'],
        ['code_afip' => '050', 'name' => 'RECIBO FACTURA A  REGIMEN DE FACTURA DE CREDITO ', 'receipt_type' => 'RECIBO', 'letter' => 'A'],
        ['code_afip' => '051', 'name' => 'FACTURAS M', 'receipt_type' => 'FACTURA', 'letter' => 'M'],
        ['code_afip' => '052', 'name' => 'NOTAS DE DEBITO M', 'receipt_type' => 'ND', 'letter' => 'M'],
        ['code_afip' => '053', 'name' => 'NOTAS DE CREDITO M', 'receipt_type' => 'NC', 'letter' => 'M'],
        ['code_afip' => '054', 'name' => 'RECIBOS M', 'receipt_type' => 'RECIBO', 'letter' => 'M'],
        ['code_afip' => '055', 'name' => 'NOTAS DE VENTA AL CONTADO M', 'receipt_type' => 'NV', 'letter' => 'M'],
        ['code_afip' => '056', 'name' => 'COMPROBANTES M DEL ANEXO I  APARTADO A  INC F   R G  N  1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'M'],
        ['code_afip' => '057', 'name' => 'OTROS COMPROBANTES M QUE CUMPLAN CON LA R G  N  1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'M'],
        ['code_afip' => '058', 'name' => 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO M', 'receipt_type' => '', 'letter' => 'M'],
        ['code_afip' => '059', 'name' => 'LIQUIDACIONES M', 'receipt_type' => 'LIQUIDACION', 'letter' => 'M'],
        ['code_afip' => '060', 'name' => 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO A', 'receipt_type' => '', 'letter' => 'A'],
        ['code_afip' => '061', 'name' => 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO B', 'receipt_type' => '', 'letter' => 'B'],
        ['code_afip' => '063', 'name' => 'LIQUIDACIONES A', 'receipt_type' => 'LIQUIDACION', 'letter' => 'A'],
        ['code_afip' => '064', 'name' => 'LIQUIDACIONES B', 'receipt_type' => 'LIQUIDACION', 'letter' => 'B'],
        ['code_afip' => '065', 'name' => 'NOTAS DE CREDITO DE COMPROBANTES CON COD. 34, 39, 58, 59, 60, 63, 96, 97 ', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '066', 'name' => 'DESPACHO DE IMPORTACION', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '067', 'name' => 'IMPORTACION DE SERVICIOS', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '068', 'name' => 'LIQUIDACION C', 'receipt_type' => 'LIQUIDACION', 'letter' => 'C'],
        ['code_afip' => '070', 'name' => 'RECIBOS FACTURA DE CREDITO', 'receipt_type' => 'RECIBO', 'letter' => ''],
        ['code_afip' => '071', 'name' => 'CREDITO FISCAL POR CONTRIBUCIONES PATRONALES', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '073', 'name' => 'FORMULARIO 1116 RT', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '074', 'name' => 'CARTA DE PORTE PARA EL TRANSPORTE AUTOMOTOR PARA GRANOS', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '075', 'name' => 'CARTA DE PORTE PARA EL TRANSPORTE FERROVIARIO PARA GRANOS', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '077', 'name' => '', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '078', 'name' => '', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '079', 'name' => '', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '080', 'name' => 'COMPROBANTE DIARIO DE CIERRE (ZETA)', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '081', 'name' => 'TIQUE FACTURA A   CONTROLADORES FISCALES', 'receipt_type' => 'TIQUE', 'letter' => 'A'],
        ['code_afip' => '082', 'name' => 'TIQUE - FACTURA B', 'receipt_type' => 'TIQUE', 'letter' => 'B'],
        ['code_afip' => '083', 'name' => 'TIQUE', 'receipt_type' => 'TIQUE', 'letter' => ''],
        ['code_afip' => '084', 'name' => 'COMPROBANTE   FACTURA DE SERVICIOS PUBLICOS   INTERESES FINANCIEROS', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '085', 'name' => 'NOTA DE CREDITO   SERVICIOS PUBLICOS   NOTA DE CREDITO CONTROLADORES FISCALES', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '086', 'name' => 'NOTA DE DEBITO   SERVICIOS PUBLICOS', 'receipt_type' => 'ND', 'letter' => ''],
        ['code_afip' => '087', 'name' => 'OTROS COMPROBANTES - SERVICIOS DEL EXTERIOR', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '088', 'name' => 'OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS / REMITO ELECTRONICO ', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '089', 'name' => 'OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS - NOTAS DE DEBITO / RESUMEN DE DATOS', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '090', 'name' => 'OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS - NOTAS DE CREDITO', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '091', 'name' => 'REMITOS R', 'receipt_type' => 'REMITO', 'letter' => 'X'],
        ['code_afip' => '092', 'name' => 'AJUSTES CONTABLES QUE INCREMENTAN EL DEBITO FISCAL', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '093', 'name' => 'AJUSTES CONTABLES QUE DISMINUYEN EL DEBITO FISCAL', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '094', 'name' => 'AJUSTES CONTABLES QUE INCREMENTAN EL CREDITO FISCAL', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '095', 'name' => 'AJUSTES CONTABLES QUE DISMINUYEN EL CREDITO FISCAL', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '096', 'name' => 'FORMULARIO 1116 B', 'receipt_type' => '', 'letter' => 'B'],
        ['code_afip' => '097', 'name' => 'FORMULARIO 1116 C', 'receipt_type' => '', 'letter' => 'C'],
        ['code_afip' => '099', 'name' => 'OTROS COMP  QUE NO CUMPLEN CON LA R G  3419 Y SUS MODIF ', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '101', 'name' => 'AJUSTE ANUAL PROVENIENTE DE LA  D J  DEL IVA  POSITIVO ', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '102', 'name' => 'AJUSTE ANUAL PROVENIENTE DE LA  D J  DEL IVA  NEGATIVO ', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '103', 'name' => 'NOTA DE ASIGNACION', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '104', 'name' => 'NOTA DE CREDITO DE ASIGNACION', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '', 'name' => 'PRESUPUESTO', 'receipt_type' => '', 'letter' => 'X'],
        ['code_afip' => '', 'name' => 'REMITO STOCK', 'receipt_type' => 'REMITO', 'letter' => 'X'],
        ['code_afip' => '', 'name' => 'DOCUMENTO NO FISCAL', 'receipt_type' => '', 'letter' => 'X'],
    ],

    'taxes' => [
        ['code_afip' => '1', 'name' => 'No Gravado', 'percent_value' => 0],
        ['code_afip' => '2', 'name' => 'Exento', 'percent_value' => 0],
        ['code_afip' => '3', 'name' => '0%', 'percent_value' => 0],
        ['code_afip' => '4', 'name' => '10,50%', 'percent_value' => 10.5],
        ['code_afip' => '5', 'name' => '21%', 'percent_value' => 21],
        ['code_afip' => '6', 'name' => '27%', 'percent_value' => 27],
    ],

    'currencies' => [
        ['code_afip' => 'PES', 'name' => 'PESOS ', 'code_iso' => 'ARS', 'symbol' => '', 'quotation_usd' => '15'],
        ['code_afip' => 'DOL', 'name' => 'Dólar ESTADOUNIDENSE ', 'code_iso' => 'USD', 'symbol' => '', 'quotation_usd' => '1'],
        ['code_afip' => '000', 'name' => 'OTRAS MONEDAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '002', 'name' => 'Dólar EEUU LIBRE ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '003', 'name' => 'FRANCOS FRANCESES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '004', 'name' => 'LIRAS ITALIANAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '005', 'name' => 'PESETAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '006', 'name' => 'MARCOS ALEMANES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '007', 'name' => 'FLORINES HOLANDESES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '008', 'name' => 'FRANCOS BELGAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '009', 'name' => 'FRANCOS SUIZOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '010', 'name' => 'PESOS MEJICANOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '011', 'name' => 'PESOS URUGUAYOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '012', 'name' => 'REAL ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '013', 'name' => 'ESCUDOS PORTUGUESES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '014', 'name' => 'CORONAS DANESAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '015', 'name' => 'CORONAS NORUEGAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '016', 'name' => 'CORONAS SUECAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '017', 'name' => 'CHELINES AUTRIACOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '018', 'name' => 'Dólar CANADIENSE ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '019', 'name' => 'YENS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '021', 'name' => 'LIBRA ESTERLINA ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '022', 'name' => 'MARCOS FINLANDESES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '023', 'name' => 'BOLIVAR (VENEZOLANO)', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '024', 'name' => 'CORONA CHECA ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '025', 'name' => 'DINAR (YUGOSLAVO) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '026', 'name' => 'Dólar AUSTRALIANO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '027', 'name' => 'DRACMA (GRIEGO) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '028', 'name' => 'FLORIN (ANTILLAS HOLA ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '029', 'name' => 'GUARANI ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '030', 'name' => 'SHEKEL (ISRAEL) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '031', 'name' => 'PESO BOLIVIANO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '032', 'name' => 'PESO COLOMBIANO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '033', 'name' => 'PESO CHILENO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '034', 'name' => 'RAND (SUDAFRICANO)', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '035', 'name' => 'NUEVO SOL PERUANO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '036', 'name' => 'SUCRE (ECUATORIANO) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '040', 'name' => 'LEI RUMANOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '041', 'name' => 'DERECHOS ESPECIALES DE GIRO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '042', 'name' => 'PESOS DOMINICANOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '043', 'name' => 'BALBOAS PANAMEÑAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '044', 'name' => 'CORDOBAS NICARAGÛENSES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '045', 'name' => 'DIRHAM MARROQUÍES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '046', 'name' => 'LIBRAS EGIPCIAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '047', 'name' => 'RIYALS SAUDITAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '048', 'name' => 'BRANCOS BELGAS FINANCIERAS', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '049', 'name' => 'GRAMOS DE ORO FINO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '050', 'name' => 'LIBRAS IRLANDESAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '051', 'name' => 'Dólar DE HONG KONG ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '052', 'name' => 'Dólar DE SINGAPUR ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '053', 'name' => 'Dólar DE JAMAICA ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '054', 'name' => 'Dólar DE TAIWAN ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '055', 'name' => 'QUETZAL (GUATEMALTECOS) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '056', 'name' => 'FORINT (HUNGRIA) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '057', 'name' => 'BAHT (TAILANDIA) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '058', 'name' => 'ECU ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '059', 'name' => 'DINAR KUWAITI ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '060', 'name' => 'EURO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '061', 'name' => 'ZLTYS POLACOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '062', 'name' => 'RUPIAS HINDÚES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '063', 'name' => 'LEMPIRAS HONDUREÑAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '064', 'name' => 'YUAN (Rep. Pop. China)', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
        ['code_afip' => '', 'name' => 'BITCOIN', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => null],
    ],

    'measures' => [
        ['code_afip' => '00', 'name' => 'SIN DESCRIPCION', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '01', 'name' => 'KILOGRAMO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '02', 'name' => 'METROS', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '03', 'name' => 'METRO CUADRADO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '04', 'name' => 'METRO CUBICO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '05', 'name' => 'LITROS', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '06', 'name' => '1000 KILOWATT HORA', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '07', 'name' => 'UNIDAD', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '08', 'name' => 'PAR', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '09', 'name' => 'DOCENA', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '10', 'name' => 'QUILATE', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '11', 'name' => 'MILLAR', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '12', 'name' => 'MEGA U. INTER. ACT. ANTIB', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '13', 'name' => 'UNIDAD INT. ACT. INMUNG', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '14', 'name' => 'GRAMO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '15', 'name' => 'MILIMETRO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '16', 'name' => 'MILIMETRO CUBICO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '17', 'name' => 'KILOMETRO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '18', 'name' => 'HECTOLITRO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '19', 'name' => 'MEGA UNIDAD INT. ACT. INMUNG', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '20', 'name' => 'CENTIMETRO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '21', 'name' => 'KILOGRAMO ACTIVO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '22', 'name' => 'GRAMO ACTIVO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '23', 'name' => 'GRAMO BASE', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '24', 'name' => 'UIACTHOR', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '25', 'name' => 'JGO.PQT. MAZO NAIPES', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '26', 'name' => 'MUIACTHOR', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '27', 'name' => 'CENTIMETRO CUBICO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '28', 'name' => 'UIACTANT', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '29', 'name' => 'TONELADA', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '30', 'name' => 'DECAMETRO CUBICO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '31', 'name' => 'HECTOMETRO CUBICO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '32', 'name' => 'KILOMETRO CUBICO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '33', 'name' => 'MICROGRAMO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '34', 'name' => 'NANOGRAMO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '35', 'name' => 'PICOGRAMO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '36', 'name' => 'MUIACTANT', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '37', 'name' => 'UIACTIG', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '41', 'name' => 'MILIGRAMO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '47', 'name' => 'MILILITRO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '48', 'name' => 'CURIE', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '49', 'name' => 'MILICURIE', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '50', 'name' => 'MICROCURIE', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '51', 'name' => 'U.INTER. ACT. HORMONAL', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '52', 'name' => 'MEGA U. INTER. ACT. HOR.', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '53', 'name' => 'KILOGRAMO BASE', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '54', 'name' => 'GRUESA', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '55', 'name' => 'MUIACTIG', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '61', 'name' => 'KILOGRAMO BRUTO', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '62', 'name' => 'PACK', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '63', 'name' => 'HORMA', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '97', 'name' => 'SEÑAS/ANTICIPOS', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '98', 'name' => 'OTRAS UNIDADES', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
        ['code_afip' => '99', 'name' => 'BONIFICACION', 'short_name' => '', 'measure_type' => '', 'factor' => '1'],
    ],

    'values' => [
        ['name' => 'client', 'type' => 'entity_type'],
        ['name' => 'supplier', 'type' => 'entity_type'],
        ['name' => 'employee', 'type' => 'entity_type'],
        ['name' => 'creditor', 'type' => 'entity_type'],
        ['name' => 'subdist', 'type' => 'entity_type'],
        ['name' => 'seller', 'type' => 'entity_type'],
        ['name' => 'subidist', 'type' => 'company_template'],
        ['name' => 'stock', 'type' => 'company_template'],
        ['name' => 'contador', 'type' => 'company_template'],
        ['name' => 'activated', 'type' => 'alias_status'],
        ['name' => 'locked', 'type' => 'alias_status'],
    ],

    'emails' => [
        [
            'name' => 'user_register',
            'subject' => '¡Bienvenido! Necesitamos que valides tu cuenta...',
            'forcompany' => 0,
            'template' => '#### ¡Bienvenido {{first_name}}!

Antes de comenzar, necesitamos que [valides tu cuenta].

Si no funciona el link, por favor copia y pega esta URL:  **{{url_activation}}**

[valides tu cuenta]: {{url_activation}}',
            'description' => 'Multinexo',
        ],
        [
            'name' => 'user_reset_password',
            'subject' => 'Reestablecimiento de contraseña',
            'forcompany' => 0,
            'template' => '#### Operación finalizada con éxito
Hola {{first_name}}, para poder finalizar el registro, debemos validar su email [This link]({{url_activation}}).

Url: **{{url_activation}}**

[This link]: {{url_activation}}',
            'description' => 'Multinexo',
        ],
        [
            'name' => 'user_invitation',
            'subject' => 'Invitación de usuario',
            'forcompany' => 0,
            'template' => '#### Operación finalizada con éxito
Hola {{first_name}}, para poder finalizar el registro, debemos validar su email [This link]({{url_activation}}).

Url: **{{url_activation}}**

[This link]: {{url_activation}}',
            'description' => 'Multinexo',
        ],
        [
            'name' => 'user_assing',
            'subject' => 'Invitación de usuario',
            'forcompany' => 0,
            'template' => '#### Operación finalizada con éxito
Hola {{invitated_first_name}}, el usuario {{first_name}} te hizo parte su empresa {{company}}.',
            'description' => 'Multinexo',
        ],
        [
            'name' => 'additional_account_validation',
            'subject' => 'Activación de cuenta adicional',
            'forcompany' => 0,
            'template' => '#### Operación finalizada con éxito
Hola {{first_name}}, para poder utilizar el correo "{{additional_account}}" como cuenta adicional debe activarla ingresando a [This link]({{url_activation}}).

Url: **{{url_activation}}**

[This link]: {{url_activation}}',
            'description' => 'Multinexo',
        ],
        [
            'name' => 'period_grace_notice',
            'subject' => 'Notificación de periodo de gracia',
            'forcompany' => 0,
            'template' => '#### Notificación de periodo de gracia
Le restan {{days}} días del periodo de gracia. ',
            'description' => 'Multinexo',
        ],
        [
            'name' => 'future_expiration_notice',
            'subject' => 'Notificación de caducidad de plan',
            'forcompany' => 0,
            'template' => '#### Aviso de vencimiento de plan 
Restan {{days}} días para que expire el plan. ',
            'description' => 'Multinexo',
        ],
        [
            'name' => 'plan_expiration_notice',
            'subject' => 'Aviso de plan caducado',
            'forcompany' => 0,
            'template' => '#### Aviso de plan caducado 
El periodo de gracia del plan _{{plan_name}}_ de la compañía _{{company_name}}_ llegó a su fin.',
            'description' => 'Multinexo',
        ],
        [
            'name' => 'failed_payment_notice',
            'subject' => 'Aviso de fallo de pago',
            'forcompany' => 0,
            'template' => '## Aviso de fallo de pago
**Motivo:**
{{reason}}

**Información de pago:**
{{external_reference}}',
            'description' => 'Multinexo',
        ],
    ],

    'responsibilities' => [
        ['code_afip' => '1', 'name' => 'IVA Responsable Inscripto', 'abbreviation' => 'RI'],
        ['code_afip' => '2', 'name' => 'IVA Responsable no Inscripto', 'abbreviation' => 'RN'],
        ['code_afip' => '3', 'name' => 'IVA no Responsable', 'abbreviation' => 'IN'],
        ['code_afip' => '4', 'name' => 'IVA Sujeto Exento', 'abbreviation' => 'IS'],
        ['code_afip' => '5', 'name' => 'Consumidor Final', 'abbreviation' => 'CF'],
        ['code_afip' => '6', 'name' => 'Responsable Monotributo', 'abbreviation' => 'MO'],
        ['code_afip' => '7', 'name' => 'Sujeto no Categorizado', 'abbreviation' => 'SC'],
        ['code_afip' => '8', 'name' => 'Proveedor del Exterior', 'abbreviation' => 'PE'],
        ['code_afip' => '9', 'name' => 'Cliente del Exterior', 'abbreviation' => 'CE'],
        ['code_afip' => '10', 'name' => 'IVA Liberado – Ley Nº 19.640', 'abbreviation' => 'IL'],
        ['code_afip' => '11', 'name' => 'IVA Responsable Inscripto – Agente de Percepción', 'abbreviation' => 'AP'],
        ['code_afip' => '12', 'name' => 'Pequeño Contribuyente Eventual', 'abbreviation' => 'PC'],
        ['code_afip' => '13', 'name' => 'Monotributista Social', 'abbreviation' => 'MS'],
        ['code_afip' => '14', 'name' => 'Pequeño Contribuyente Eventual Social', 'abbreviation' => 'PS'],
    ],

    'permissions' => [
        ['inherit_id' => null, 'name' => 'manual', 'slug' => '', 'description' => 'Manage manual permissions'],
        ['inherit_id' => null, 'name' => 'manual.allowStockNegative', 'slug' => 'stockNegative', 'description' => 'Selects stock negative / no stock']
    ],

    'aliases' => [
        [
            'name' => 'Detalles', 'slug' => 'detail',
            'permissions' => [
                'detail.allowDestroyForInvoices',
                'detail.allowDestroyForOrders',
                'detail.allowDestroyForQuotations',
                'detail.allowIndexForInvoices',
                'detail.allowIndexForOrders',
                'detail.allowIndexForQuotations',
                'detail.allowShowForInvoices',
                'detail.allowShowForOrders',
                'detail.allowShowForQuotations',
                'detail.allowStoreForInvoices',
                'detail.allowStoreForOrders',
                'detail.allowStoreForQuotations',
                'detail.allowUpdateForInvoices',
                'detail.allowUpdateForOrders',
                'detail.allowUpdateForQuotations'
            ],
        ],
        [
            'name' => 'Params', 'slug' => 'params',
            'permissions' => [
                'params.allowPutParamsUser',
            ],
        ],

        [
            'name' => 'Documentos', 'slug' => 'documents',
            'permissions' => [
                'document.allowIndex',
                'document.allowShow',
                'document.allowUpdateClosureReceipt',
            ],
        ],

        [
            'name' => 'Entidades', 'slug' => 'entities',
            'permissions' => [
                'entity.allowDestroy',
                'entity.allowGetTransactions',
                'entity.allowIndex',
                'entity.allowShow',
                'entity.allowStore',
                'entity.allowUpdate',
            ],
        ],

        [
            'name' => 'Libro Fiscal', 'slug' => 'fiscalbooks',
            'permissions' => [
                'fiscalbook.allowFiscalBookPdf',
                'fiscalbook.allowIndex',
                'fiscalbook.allowShow',
                'fiscalbook.allowStore',
                'fiscalbook.allowFiscalBookCiti',
                'fiscalbook.allowFiscalBookCsv',
                'fiscalbook.allowFiscalBookPdf',
                'fiscalbook.allowFiscalBookXls',
            ],
        ],

        [
            'name' => 'Fiscal POS', 'slug' => 'fiscalpos',
            'permissions' => [
                'fiscalpos.allowDestroy',
                'fiscalpos.allowIndex',
                'fiscalpos.allowShow',
                'fiscalpos.allowStore',
                'fiscalpos.allowUpdate',
                'fiscalpos.allowUpdateFromWs',
            ],
        ],

        [

            'name' => 'Precios Futuros', 'slug' => 'future_prices',
            'permissions' => [
                'futurePrice.allowDestroy',
                'futurePrice.allowIndex',
                'futurePrice.allowShow',
                'futurePrice.allowStore',
                'futurePrice.allowUpdate',
            ],
        ],

        [
            'name' => 'Precios Gondolas', 'slug' => 'gondola_prices',
            'permissions' => [
                'gondolaPrice.allowDestroy',
                'gondolaPrice.allowIndex',
                'gondolaPrice.allowShow',
                'gondolaPrice.allowStore',
            ],
        ],

        [
            'name' => 'Inventario', 'slug' => 'inventories',
            'permissions' => [
                'inventory.allowIndex',
            ],
        ],

        [
            'name' => 'Facturas', 'slug' => 'invoices',
            'permissions' => [
                'invoice.allowDestroy',
                'invoice.allowIndex',
                'invoice.allowShow',
                'invoice.allowStore',
                'invoice.allowUpdate',
                'invoice.allowGetCae',
            ],
        ],

        [
            'name' => 'Documentos no Fiscales', 'slug' => 'no_fiscal_documents',
            'permissions' => [
                'no_fiscal_document.allowDestroy',
                'no_fiscal_document.allowIndex',
                'no_fiscal_document.allowShow',
                'no_fiscal_document.allowStore',
                'no_fiscal_document.allowUpdate',
            ],
        ],

        [
            'name' => 'Remitos', 'slug' => 'orders',
            'permissions' => [
                'order.allowDestroy',
                'order.allowIndex',
                'order.allowShow',
                'order.allowStore',
                'order.allowUpdate',
            ],
        ],

        [
            'name' => 'Lista de Precios', 'slug' => 'pricelists',
            'permissions' => [
                'pricelist.allowDestroy',
                'pricelist.allowIndex',
                'pricelist.allowShow',
                'pricelist.allowStore',
                'pricelist.allowUpdate',
            ],
        ],

        [
            'name' => 'Precios', 'slug' => 'pricelist_products',
            'permissions' => [
                'pricelistProduct.allowDestroy',
                'pricelistProduct.allowIndex',
                'pricelistProduct.allowShow',
                'pricelistProduct.allowStoreOrUpdate',
                'pricelistProduct.allowUpdate',
            ],
        ],

        [
            'name' => 'Productos', 'slug' => 'products',
            'permissions' => [
                'product.allowDestroy',
                'product.allowIndex',
                'product.allowIndexPrice',
                'product.allowShow',
                'product.allowStore',
                'product.allowUpdate',
                'product.allowUpdateUploadPhoto',
                'product.allowUploadPhoto',
            ],
        ],

        [
            'name' => 'Inventario de Productos', 'slug' => 'product_inventories',
            'permissions' => [
                'productInventory.allowIndex',
                'productInventory.allowShow',
            ],
        ],

        [
            'name' => 'Presupuestos', 'slug' => 'quotations',
            'permissions' => [
                'quotation.allowDestroy',
                'quotation.allowIndex',
                'quotation.allowShow',
                'quotation.allowStore',
                'quotation.allowUpdate',
            ],
        ],

        [
            'name' => 'Roles', 'slug' => 'roles',
            'permissions' => [
                'role.allowDestroy',
                'role.allowRolesByCompany',
                'role.allowShow',
                'role.allowStore',
                'role.allowUpdate',
            ],
        ],

        [
            'name' => 'Transacciones', 'slug' => 'transactions',
            'permissions' => [
                'transaction.allowIndex',
                'transaction.allowShow',
                'transaction.allowStore',
                'transaction.allowUpdate',
            ],
        ],

        [
            'name' => 'Stock negativo', 'slug' => 'stock_negative',
            'permissions' => [
                'manual.allowStockNegative'
            ],
        ],

        [
            'name' => 'Alias', 'slug' => 'alises',
            'permissions' => [
                'alias.allowIndex'
            ],
        ],

        [
            'name' => 'Categorias', 'slug' => 'categories',
            'permissions' => [
                'category.allowDestroy',
                'category.allowIndex',
                'category.allowShow',
                'category.allowStore',
                'category.allowUpdate'
            ],
        ],

        [
            'name' => 'Cierres Z', 'slug' => 'closures',
            'permissions' => [
                'closure_receipt.allowIndex',
                'closure_receipt.allowShow',
                'closure_receipt.allowStore',
                'closure_receipt.allowUpdate'
            ],
        ],

        [
            'name' => 'Empresa', 'slug' => 'companies',
            'permissions' => [
                'company.allowDestroy',
                'company.allowRestore',
                'company.allowShow',
                'company.allowUpdate',
                'company.allowUploadLogo',
                'company.allowEstablishDefaultAfipWs',
            ],
        ],

        [
            'name' => 'Usuarios', 'slug' => 'users',
            'permissions' => [
                'user.allowIndex',
                'user.allowMailAssign',
                'user.allowRoleUpdate'
            ],
        ],

        [
            'name' => 'Yo', 'slug' => 'users_me', 'status' => 'locked',
            'permissions' => [
                'user.allowGetPermissions'
            ],
        ],
        [
            'name' => 'Configurar Factura Electronica', 'slug' => 'electronic_invoices',
            'permissions' => [
                'company.allowCheckWsAfipStatus',
                'company.allowDownloadCsr',
                'company.allowUploadAfipCertificate'
            ],
        ],
        [
            'name' => 'Ganancias', 'slug' => 'revenues',
            'permissions' => [
                'revenue.allowIndex',
            ],
        ],
        [
            'name' => 'Disponibilidades', 'slug' => 'availabilities',
            'permissions' => [
                'availability.allowDestroy',
                'availability.allowIndex',
                'availability.allowShow',
                'availability.allowStore',
                'availability.allowUpdate',
            ],
        ],
        [
            'name' => 'Exportar xls', 'slug' => 'export_xls',
            'permissions' => [
                'export.allowXls_pdf',
            ],
        ],
        [
            'name' => 'Sistema de pagos', 'slug' => 'company_payments',
            'permissions' => [
                'company_payment.allowIndex',
                'company_payment.allowShow',
            ],
        ],
        [
            'name' => 'Registro de documentos', 'slug' => 'document_logs',
            'permissions' => [
                'document_log.allowIndex',
                'document_log.allowShow',
            ],
        ],
    ],

    'users' => [
        [
            'first_name' => 'Demo',
            'last_name' => 'Demo',
            'email' => 'demo@multinexo.com',
            'password' => 'multinexo',
            'activated' => '1',
            'super_admin' => '1',
            'remember_token' => 'KT051o47lH',
            //'activation_code' => ''
        ],
        [
            'first_name' => 'Seed',
            'last_name' => 'Seed',
            'email' => 'seed@multinexo.com',
            'password' => 'multinexo',
            'activated' => '1',
            'super_admin' => '1',
            'remember_token' => 'KT051o47lH',
            //'activation_code' => ''
        ]
    ],

    'companies' => [
        [
            'name' => 'Mi empresa',
            'status' => '1',
            'user_id' => 0,
            'abbreviation' => 'me',
            'description' => 'Empresa de prueba',
            'cuit' => '20999999991',
            'street_name' => 'Calle',
            'street_number' => '123',
            'phone' => '2604999999',
            'fiscal_ws_status' => '0',
            'responsibility_id' => 5,
        ],
        [
            'name' => 'Reyesoft',
            'status' => '1',
            'user_id' => 0,
            'abbreviation' => 'RS',
            'description' => '',
            'cuit' => '20305423174',
            'street_name' => 'Vicente Lopez y Planes',
            'street_number' => '2248',
            'phone' => '2604558293',
            'fiscal_ws_status' => '1',
            'responsibility_id' => 1,
        ]
    ],

    'pricelists_template' => [
        [
            'name' => 'Público',
            'company_id' => 0,
            'percent_price' => '40.00',
            'percent_subdist' => '0.00',
            'percent_prevent' => '9.00',
            'type' => 'company_template'
        ],
        [
            'name' => 'Comercio',
            'company_id' => 0,
            'percent_price' => '24.00',
            'percent_subdist' => '0.00',
            'percent_prevent' => '4.00'
        ],
        [
            'name' => 'Mayorista',
            'company_id' => 0,
            'percent_price' => '21.00',
            'percent_subdist' => '0.00',
            'percent_prevent' => '3.00'
        ],
    ],

    'pricelists' => [
        [
            'name' => 'Público',
            'company_id' => 0,
            'percent_price' => '40.00',
            'percent_subdist' => '0.00',
            'percent_prevent' => '9.00',
        ],
        [
            'name' => 'Comercio',
            'company_id' => 0,
            'percent_price' => '24.00',
            'percent_subdist' => '0.00',
            'percent_prevent' => '4.00'
        ],
        [
            'name' => 'Mayorista',
            'company_id' => 0,
            'percent_price' => '21.00',
            'percent_subdist' => '0.00',
            'percent_prevent' => '3.00'
        ],
        [
            'name' => 'Negocio',
            'company_id' => 0,
            'percent_price' => '26.00',
            'percent_subdist' => '0.00',
            'percent_prevent' => '5.00'
        ],
        [
            'name' => 'Mayorista espec',
            'company_id' => 0,
            'percent_price' => '21.00',
            'percent_subdist' => '0.00',
            'percent_prevent' => '4.00'
        ]
    ],

    'categories' => [
        ['name' => 'Varios'],
        ['name' => 'Algodones'],
        ['name' => 'Pegamentos'],
        ['name' => 'Perfumeria - Cuidados cabello'],
        ['name' => 'Perfumeria - Pastas dentales'],
        ['name' => 'Perfumeria - Cuidado bucal'],
        ['name' => 'Lavandinas'],
        ['name' => 'Desodorantes de ambientes'],
        ['name' => 'Desodorantes y limp de pisos'],
        ['name' => 'Limpiadores hogar'],
        ['name' => 'Prelavados'],
        ['name' => 'Aditivos'],
        ['name' => 'Utensilios de limpieza'],
        ['name' => 'Insecticidas aerosol'],
        ['name' => 'Papelera'],
        ['name' => 'Detergentes para ropa'],
        ['name' => 'Detergentes para vajilla'],
        ['name' => 'Automotores'],
        ['name' => 'Perfumería'],
        ['name' => 'Suavizantes para la ropa'],
        ['name' => 'Detergentes para lavavajillas'],
        ['name' => 'Perfumería - Jabon de tocador'],
        ['name' => 'Plasticos'],
        ['name' => 'Utensilios de cocina'],
        ['name' => 'Utensilios personales'],
        ['name' => 'Jabones en pan'],
        ['name' => 'Toallitas Femeninas'],
        ['name' => 'Protectores'],
        ['name' => 'Pañales Adultos'],
        ['name' => 'Pañales'],
        ['name' => 'Perfumeria - Talcos'],
        ['name' => 'Perfumeria - Talcos aerosol'],
        ['name' => 'Perfumería - desodorantes aero'],
        ['name' => 'Galletas'],
        ['name' => 'Perfumeria - Cremas'],
        ['name' => 'Protectores Mamarios'],
        ['name' => 'Perfumeria anexo bebé'],
        ['name' => 'Textiles - Rejillas'],
        ['name' => 'Textiles - Trapos de piso'],
        ['name' => 'Textiles'],
        ['name' => 'Plásticos - Macetas'],
        ['name' => 'Cuidado de muebles'],
        ['name' => 'Cuidado de pisos'],
        ['name' => 'Insecticidas'],
        ['name' => 'Lámparas'],
        ['name' => 'Lámparas - Bajo consumo'],
        ['name' => 'Alcoholes'],
        ['name' => 'Perfumería - Jabon líq corpora'],
        ['name' => 'Perfumería - Jabón liquido'],
        ['name' => 'Perfumeria - bronceadores'],
        ['name' => 'Cuidados de la ropa - Quitaman'],
        ['name' => 'Cuidados de la ropa'],
        ['name' => 'Cuidado de la ropa - Apresto'],
        ['name' => 'Cuidados del calzado'],
        ['name' => 'Limpiadores hogar - Baño'],
        ['name' => 'Industriales - Sanitizantes'],
        ['name' => 'Industriales - Vajilla'],
        ['name' => 'Industriales -'],
        ['name' => 'Industriales - Desengrasantes'],
        ['name' => 'Industriales - Limpiadores'],
        ['name' => 'Industriales - Lavavajillas'],
        ['name' => 'Industriales - Aromatizante'],
        ['name' => 'Perfumeria - Geles'],
        ['name' => 'Vinos - Espumantes'],
        ['name' => 'Vinos'],
        ['name' => 'Espumantes'],
        ['name' => 'Papelera - Higiénicos'],
        ['name' => 'Industriales - Papelera'],
        ['name' => 'Perfumeria - desodorantes'],
        ['name' => 'PRECIOS CUIDADOS'],
        ['name' => 'Detergentes para ropa líquidos'],
        ['name' => 'Plásticos - Jardinería'],
        ['name' => 'Plásticos - Sanidad'],
    ],

    'products' => [
        [
            'name' => 'Martillo Thor',
            'description' => 'descripción producto martillo de thor.',
            'author_id' => 0,
            'company_id' => 0,
            'currency_id' => '1',
            'stock' => '0',
            'replacement_cost' => '200',
            'category_id' => 0,
            'duration' => '0',
            'product_type' => 'product',
            'tax_id' => 5,
            'stock_type' => 'negative',
            'sku' => '110011',
            'conduct' => 'common',
            'stock_alert' => '5',
            'stock_desired' => '5',

        ],
        [
            'name' => 'Casco Iron Man',
            'description' => 'descripción producto casco iron man.',
            'author_id' => 0,
            'company_id' => 0,
            'currency_id' => '1',
            'stock' => '0',
            'replacement_cost' => '150',
            'category_id' => 0,
            'duration' => '0',
            'product_type' => 'product',
            'tax_id' => 5,
            'stock_type' => 'negative',
            'sku' => '001100',
            'conduct' => 'common',
            'stock_alert' => '5',
            'stock_desired' => '5',
        ],
        [
            'name' => 'ponds age miracle serum restaurador',
            'sku' => '8901030202000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 62.74,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 1,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => -2,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'kotex toallas humedas evolution 20u',
            'sku' => '7702425538000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 14.88,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 19,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => 360,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'rvk rejilla crochet k art 424',
            'sku' => '7798069221000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 3.45,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 40,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => 36,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'mr fresh canasta liq full floral',
            'sku' => '7798136040000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 26.2,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 1,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => 27,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'cotton up hisopos con espejo 80u',
            'sku' => '7790900030000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 10.38,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 1,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => -1,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'brasso brillametal liquido 504ml',
            'sku' => '7791130140000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 36.32,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 10,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => 39,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'polycera cera liq roja dp 400ml',
            'sku' => '7791130002000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 16.33,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 43,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => 41,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'koleston oxi 30v',
            'sku' => '7896016123000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 2.50,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 1,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => -17,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'veritas des rollon men active',
            'sku' => '7791520024000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 16.64,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 69,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => -1,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'chemoxane f insecticida 50g',
            'sku' => '7798084690000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 24,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 1,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => 0,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'matriplaster fregona 14l',
            'sku' => '8412524010000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 53.70,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 1,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => '-161',
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
        [
            'name' => 'fregona repuesto',
            'sku' => '8412524013000',
            'conduct' => 'common',
            'product_type' => 'product',
            'stock_type' => 'negative',
            'replacement_cost' => 13.94,
            'author_id' => 0,
            'company_id' => 0,
            'category_id' => 1,
            'tax_id' => 5,
            'currency_id' => 1,
            'stock' => 357,
            'stock_alert' => 0,
            'stock_desired' => 0,
        ],
    ],

    'roles' => [
        [
            'name' => 'Administrador',
            'slug' => 'administrador',
            'type' => 'admin',
            'description' => '',
            'company_id' => 0,
        ],
    ],

    'entities' => [
        [
            'company_id' => 0,
            'author_id' => 0,
            'name' => 'Juan Perez',
            'seller_id' => 0,
            'identification_id' => 25,
            'identification_number' => 20327936221,
            'contact_name' => 'contact name',
            'street_name' => 'Avenida Siempreviva',
            'street_number' => '742',
            'location' => 'San rafaEl',
            'province' => 'MenDoza',
            'additional_info' => 'aditional info',
            'email' => 'juan_perez@multinexo.com',
            'phone' => '0800-555-2112',
            'pricelist_id' => 0,
            'entity_type' => 'client',
            'responsibility_id' => 1,
        ],
        [
            'company_id' => 0,
            'author_id' => 0,
            'name' => 'Augusto Martinez',
            'seller_id' => 0,
            'identification_id' => 25,
            'identification_number' => 20327936221,
            'contact_name' => 'contact name',
            'street_name' => 'Wallaby',
            'street_number' => '42',
            'location' => 'San rafaEl',
            'province' => 'MenDoza',
            'additional_info' => 'aditional info',
            'email' => 'augusto_martinez@gmail.com',
            'phone' => '0800-555-9999',
            'pricelist_id' => 0,
            'entity_type' => 'seller',
            'responsibility_id' => 1,
        ],
        [
            'company_id' => 0,
            'author_id' => 0,
            'name' => 'Nelson Martin',
            'seller_id' => 0,
            'identification_id' => 25,
            'identification_number' => 20327936221,
            'contact_name' => 'contact name',
            'street_name' => 'Concordia',
            'street_number' => '87',
            'location' => 'San rafaEl',
            'province' => 'MenDoza',
            'additional_info' => 'aditional info',
            'email' => 'nelson_martin@multinexo.com',
            'phone' => '0800-555-9999',
            'pricelist_id' => 0,
            'entity_type' => 'subdist',
            'responsibility_id' => 1,
        ],
        [
            'company_id' => 0,
            'author_id' => 0,
            'name' => 'Proveedor el gran',
            'seller_id' => 0,
            'identification_id' => 25,
            'identification_number' => 20369952624,
            'contact_name' => 'contact name',
            'street_name' => 'street name',
            'location' => 'San rafaEl',
            'province' => 'MenDoza',
            'street_number' => '9911',
            'additional_info' => 'aditional info',
            'email' => 'elgran@multinexo.com',
            'phone' => '0800-555-9999',
            'pricelist_id' => 0,
            'entity_type' => 'supplier',
            'responsibility_id' => 1,
        ],
        [
            'company_id' => 0,
            'author_id' => 0,
            'name' => 'Consumidor final',
            'seller_id' => 0,
            'identification_id' => 36,
            'identification_number' => 0,
            'contact_name' => '',
            'street_name' => '',
            'street_number' => '',
            'additional_info' => '',
            'email' => '',
            'phone' => '',
            'pricelist_id' => 0,
            'entity_type' => 'client',
            'responsibility_id' => 5,
        ]
    ],

    'plans' => [
        ['name' => 'Free', 'key' => 'free', 'amount' => '0', 'limit' => '150', 'price_per_document' => ''],
        ['name' => 'Amarillo', 'key' => 'amarillo', 'amount' => '800', 'limit' => '500', 'price_per_document' => '0.8'],
        ['name' => 'Azul', 'key' => 'azul', 'amount' => '1300', 'limit' => '5000', 'price_per_document' => '1.3'],
        ['name' => 'Rojo', 'key' => 'rojo', 'amount' => '3000', 'limit' => '10000', 'price_per_document' => '3'],
    ],

    'discounts' => [
        ['months' => '3', 'percent' => 5],
        ['months' => '6', 'percent' => 10],
        ['months' => '12', 'percent' => 25],
    ],
];