<?php

return [

    'identifications' => [
        ['code_afip' => '0', 'name' => 'CI Policía Federal'],
        ['code_afip' => '1', 'name' => 'CI Buenos Aires'],
        ['code_afip' => '2', 'name' => 'CI Catamarca'],
        ['code_afip' => '3', 'name' => 'CI Córdoba'],
        ['code_afip' => '4', 'name' => 'CI Corrientes'],
        ['code_afip' => '5', 'name' => 'CI Entre Ríos'],
        ['code_afip' => '6', 'name' => 'CI Jujuy'],
        ['code_afip' => '7', 'name' => 'CI Mendoza'],
        ['code_afip' => '8', 'name' => 'CI La Rioja'],
        ['code_afip' => '9', 'name' => 'CI Salta'],
        ['code_afip' => '10', 'name' => 'CI San Juan'],
        ['code_afip' => '11', 'name' => 'CI San Luis'],
        ['code_afip' => '12', 'name' => 'CI Santa Fe'],
        ['code_afip' => '13', 'name' => 'CI Santiago del Estero'],
        ['code_afip' => '14', 'name' => 'CI Tucumán'],
        ['code_afip' => '16', 'name' => 'CI Chaco'],
        ['code_afip' => '17', 'name' => 'CI Chubut'],
        ['code_afip' => '18', 'name' => 'CI Formosa'],
        ['code_afip' => '19', 'name' => 'CI Misiones'],
        ['code_afip' => '20', 'name' => 'CI Neuquén'],
        ['code_afip' => '21', 'name' => 'CI La Pampa'],
        ['code_afip' => '22', 'name' => 'CI Río Negro'],
        ['code_afip' => '23', 'name' => 'CI Santa Cruz'],
        ['code_afip' => '24', 'name' => 'CI Tierra del Fuego'],
        ['code_afip' => '80', 'name' => 'CUIT'],
        ['code_afip' => '86', 'name' => 'CUIL'],
        ['code_afip' => '87', 'name' => 'CDI'],
        ['code_afip' => '89', 'name' => 'LE'],
        ['code_afip' => '90', 'name' => 'LC'],
        ['code_afip' => '91', 'name' => 'CI extranjera'],
        ['code_afip' => '92', 'name' => 'en trámite'],
        ['code_afip' => '93', 'name' => 'Acta nacimiento'],
        ['code_afip' => '94', 'name' => 'Pasaporte'],
        ['code_afip' => '95', 'name' => 'CI Bs. As. RNP'],
        ['code_afip' => '96', 'name' => 'DNI'],
        ['code_afip' => '99', 'name' => 'Sin identificar/venta global diaria'],
        ['code_afip' => '30', 'name' => 'Certificado de Migración'],
        ['code_afip' => '88', 'name' => 'Usado por Anses para Padrón'],
    ],

    'receipts' => [
        ['code_afip' => '001', 'name' => 'FACTURAS A', 'receipt_type' => 'FACTURA', 'letter' => 'A'],
        ['code_afip' => '002', 'name' => 'NOTAS DE DEBITO A', 'receipt_type' => 'ND', 'letter' => 'A'],
        ['code_afip' => '003', 'name' => 'NOTAS DE CREDITO A', 'receipt_type' => 'NC', 'letter' => 'A'],
        ['code_afip' => '004', 'name' => 'RECIBOS A', 'receipt_type' => 'RECIBO', 'letter' => 'A'],
        ['code_afip' => '005', 'name' => 'NOTAS DE VENTA AL CONTADO A', 'receipt_type' => 'NV', 'letter' => 'A'],
        ['code_afip' => '006', 'name' => 'FACTURAS B', 'receipt_type' => 'FACTURA', 'letter' => 'B'],
        ['code_afip' => '007', 'name' => 'NOTAS DE DEBITO B', 'receipt_type' => 'ND', 'letter' => 'B'],
        ['code_afip' => '008', 'name' => 'NOTAS DE CREDITO B', 'receipt_type' => 'NC', 'letter' => 'B'],
        ['code_afip' => '009', 'name' => 'RECIBOS B', 'receipt_type' => 'RECIBO', 'letter' => 'B'],
        ['code_afip' => '010', 'name' => 'NOTAS DE VENTA AL CONTADO B', 'receipt_type' => 'NV', 'letter' => 'B'],
        ['code_afip' => '011', 'name' => 'FACTURAS C', 'receipt_type' => 'FACTURA', 'letter' => 'C'],
        ['code_afip' => '012', 'name' => 'NOTAS DE DEBITO C', 'receipt_type' => 'ND', 'letter' => 'C'],
        ['code_afip' => '013', 'name' => 'NOTAS DE CREDITO C', 'receipt_type' => 'NC', 'letter' => 'C'],
        ['code_afip' => '014', 'name' => 'DOCUMENTO ADUANERO', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '015', 'name' => 'RECIBOS C', 'receipt_type' => 'RECIBO', 'letter' => 'C'],
        ['code_afip' => '016', 'name' => 'NOTAS DE VENTA AL CONTADO C', 'receipt_type' => 'NV', 'letter' => 'C'],
        ['code_afip' => '019', 'name' => 'FACTURAS DE EXPORTACION', 'receipt_type' => 'FACTURA', 'letter' => ''],
        ['code_afip' => '020', 'name' => 'NOTAS DE DEBITO POR OPERACIONES CON EL EXTERIOR', 'receipt_type' => 'ND', 'letter' => ''],
        ['code_afip' => '021', 'name' => 'NOTAS DE CREDITO POR OPERACIONES CON EL EXTERIOR', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '022', 'name' => 'FACTURAS - PERMISO EXPORTACION SIMPLIFICADO - DTO. 855/97', 'receipt_type' => 'FACTURA', 'letter' => ''],
        ['code_afip' => '030', 'name' => 'COMPROBANTES DE COMPRA DE BIENES USADOS', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '031', 'name' => 'MANDATO - CONSIGNACION', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '032', 'name' => 'COMPROBANTES PARA RECICLAR MATERIALES', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '034', 'name' => 'COMPROBANTES A DEL APARTADO A  INCISO F  R G  N  1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'A'],
        ['code_afip' => '035', 'name' => 'COMPROBANTES B DEL ANEXO I, APARTADO A, INC. F), RG N° 1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'B'],
        ['code_afip' => '036', 'name' => 'COMPROBANTES C DEL Anexo I, Apartado A, INC.F), R.G. N° 1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'C'],
        ['code_afip' => '037', 'name' => 'NOTAS DE DEBITO O DOCUMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415', 'receipt_type' => 'ND', 'letter' => ''],
        ['code_afip' => '038', 'name' => 'NOTAS DE CREDITO O DOCMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '039', 'name' => 'OTROS COMPROBANTES A QUE CUMPLEN CON LA R G  1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'A'],
        ['code_afip' => '040', 'name' => 'OTROS COMPROBANTES B QUE CUMPLAN CON LA R.G. N° 1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'B'],
        ['code_afip' => '041', 'name' => 'OTROS COMPROBANTES C QUE CUMPLAN CON LA R.G. N° 1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'C'],
        ['code_afip' => '050', 'name' => 'RECIBO FACTURA A  REGIMEN DE FACTURA DE CREDITO ', 'receipt_type' => 'RECIBO', 'letter' => 'A'],
        ['code_afip' => '051', 'name' => 'FACTURAS M', 'receipt_type' => 'FACTURA', 'letter' => 'M'],
        ['code_afip' => '052', 'name' => 'NOTAS DE DEBITO M', 'receipt_type' => 'ND', 'letter' => 'M'],
        ['code_afip' => '053', 'name' => 'NOTAS DE CREDITO M', 'receipt_type' => 'NC', 'letter' => 'M'],
        ['code_afip' => '054', 'name' => 'RECIBOS M', 'receipt_type' => 'RECIBO', 'letter' => 'M'],
        ['code_afip' => '055', 'name' => 'NOTAS DE VENTA AL CONTADO M', 'receipt_type' => 'NV', 'letter' => 'M'],
        ['code_afip' => '056', 'name' => 'COMPROBANTES M DEL ANEXO I  APARTADO A  INC F   R G  N  1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'M'],
        ['code_afip' => '057', 'name' => 'OTROS COMPROBANTES M QUE CUMPLAN CON LA R G  N  1415', 'receipt_type' => 'COMPROBANTE', 'letter' => 'M'],
        ['code_afip' => '058', 'name' => 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO M', 'receipt_type' => '', 'letter' => 'M'],
        ['code_afip' => '059', 'name' => 'LIQUIDACIONES M', 'receipt_type' => 'LIQUIDACION', 'letter' => 'M'],
        ['code_afip' => '060', 'name' => 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO A', 'receipt_type' => '', 'letter' => 'A'],
        ['code_afip' => '061', 'name' => 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO B', 'receipt_type' => '', 'letter' => 'B'],
        ['code_afip' => '063', 'name' => 'LIQUIDACIONES A', 'receipt_type' => 'LIQUIDACION', 'letter' => 'A'],
        ['code_afip' => '064', 'name' => 'LIQUIDACIONES B', 'receipt_type' => 'LIQUIDACION', 'letter' => 'B'],
        ['code_afip' => '065', 'name' => 'NOTAS DE CREDITO DE COMPROBANTES CON COD. 34, 39, 58, 59, 60, 63, 96, 97 ', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '066', 'name' => 'DESPACHO DE IMPORTACION', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '067', 'name' => 'IMPORTACION DE SERVICIOS', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '068', 'name' => 'LIQUIDACION C', 'receipt_type' => 'LIQUIDACION', 'letter' => 'C'],
        ['code_afip' => '070', 'name' => 'RECIBOS FACTURA DE CREDITO', 'receipt_type' => 'RECIBO', 'letter' => ''],
        ['code_afip' => '071', 'name' => 'CREDITO FISCAL POR CONTRIBUCIONES PATRONALES', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '073', 'name' => 'FORMULARIO 1116 RT', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '074', 'name' => 'CARTA DE PORTE PARA EL TRANSPORTE AUTOMOTOR PARA GRANOS', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '075', 'name' => 'CARTA DE PORTE PARA EL TRANSPORTE FERROVIARIO PARA GRANOS', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '077', 'name' => '', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '078', 'name' => '', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '079', 'name' => '', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '080', 'name' => 'COMPROBANTE DIARIO DE CIERRE (ZETA)', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '081', 'name' => 'TIQUE FACTURA A   CONTROLADORES FISCALES', 'receipt_type' => 'TIQUE', 'letter' => 'A'],
        ['code_afip' => '082', 'name' => 'TIQUE - FACTURA B', 'receipt_type' => 'TIQUE', 'letter' => 'B'],
        ['code_afip' => '083', 'name' => 'TIQUE', 'receipt_type' => 'TIQUE', 'letter' => ''],
        ['code_afip' => '084', 'name' => 'COMPROBANTE   FACTURA DE SERVICIOS PUBLICOS   INTERESES FINANCIEROS', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '085', 'name' => 'NOTA DE CREDITO   SERVICIOS PUBLICOS   NOTA DE CREDITO CONTROLADORES FISCALES', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '086', 'name' => 'NOTA DE DEBITO   SERVICIOS PUBLICOS', 'receipt_type' => 'ND', 'letter' => ''],
        ['code_afip' => '087', 'name' => 'OTROS COMPROBANTES - SERVICIOS DEL EXTERIOR', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '088', 'name' => 'OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS / REMITO ELECTRONICO ', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '089', 'name' => 'OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS - NOTAS DE DEBITO / RESUMEN DE DATOS', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '090', 'name' => 'OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS - NOTAS DE CREDITO', 'receipt_type' => 'COMPROBANTE', 'letter' => ''],
        ['code_afip' => '091', 'name' => 'REMITOS R', 'receipt_type' => 'REMITO', 'letter' => 'X'],
        ['code_afip' => '092', 'name' => 'AJUSTES CONTABLES QUE INCREMENTAN EL DEBITO FISCAL', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '093', 'name' => 'AJUSTES CONTABLES QUE DISMINUYEN EL DEBITO FISCAL', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '094', 'name' => 'AJUSTES CONTABLES QUE INCREMENTAN EL CREDITO FISCAL', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '095', 'name' => 'AJUSTES CONTABLES QUE DISMINUYEN EL CREDITO FISCAL', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '096', 'name' => 'FORMULARIO 1116 B', 'receipt_type' => '', 'letter' => 'B'],
        ['code_afip' => '097', 'name' => 'FORMULARIO 1116 C', 'receipt_type' => '', 'letter' => 'C'],
        ['code_afip' => '099', 'name' => 'OTROS COMP  QUE NO CUMPLEN CON LA R G  3419 Y SUS MODIF ', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '101', 'name' => 'AJUSTE ANUAL PROVENIENTE DE LA  D J  DEL IVA  POSITIVO ', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '102', 'name' => 'AJUSTE ANUAL PROVENIENTE DE LA  D J  DEL IVA  NEGATIVO ', 'receipt_type' => 'AJUSTE', 'letter' => ''],
        ['code_afip' => '103', 'name' => 'NOTA DE ASIGNACION', 'receipt_type' => '', 'letter' => ''],
        ['code_afip' => '104', 'name' => 'NOTA DE CREDITO DE ASIGNACION', 'receipt_type' => 'NC', 'letter' => ''],
        ['code_afip' => '', 'name' => 'PRESUPUESTO', 'receipt_type' => '', 'letter' => 'X'],
        ['code_afip' => '', 'name' => 'REMITO STOCK', 'receipt_type' => 'REMITO', 'letter' => 'X'],
        ['code_afip' => '', 'name' => 'DOCUMENTO NO FISCAL', 'receipt_type' => '', 'letter' => 'X'],
    ],

    'currencies' => [
        ['code_afip' => 'PES', 'name' => 'PESOS ', 'code_iso' => 'ARS', 'symbol' => '', 'quotation_usd' => '15'],
        ['code_afip' => 'DOL', 'name' => 'Dólar ESTADOUNIDENSE ', 'code_iso' => 'USD', 'symbol' => '', 'quotation_usd' => '1'],
        ['code_afip' => '000', 'name' => 'OTRAS MONEDAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '002', 'name' => 'Dólar EEUU LIBRE ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '003', 'name' => 'FRANCOS FRANCESES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '004', 'name' => 'LIRAS ITALIANAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '005', 'name' => 'PESETAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '006', 'name' => 'MARCOS ALEMANES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '007', 'name' => 'FLORINES HOLANDESES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '008', 'name' => 'FRANCOS BELGAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '009', 'name' => 'FRANCOS SUIZOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '010', 'name' => 'PESOS MEJICANOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '011', 'name' => 'PESOS URUGUAYOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '012', 'name' => 'REAL ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '013', 'name' => 'ESCUDOS PORTUGUESES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '014', 'name' => 'CORONAS DANESAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '015', 'name' => 'CORONAS NORUEGAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '016', 'name' => 'CORONAS SUECAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '017', 'name' => 'CHELINES AUTRIACOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '018', 'name' => 'Dólar CANADIENSE ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '019', 'name' => 'YENS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '021', 'name' => 'LIBRA ESTERLINA ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '022', 'name' => 'MARCOS FINLANDESES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '023', 'name' => 'BOLIVAR (VENEZOLANO)', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '024', 'name' => 'CORONA CHECA ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '025', 'name' => 'DINAR (YUGOSLAVO) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '026', 'name' => 'Dólar AUSTRALIANO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '027', 'name' => 'DRACMA (GRIEGO) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '028', 'name' => 'FLORIN (ANTILLAS HOLA ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '029', 'name' => 'GUARANI ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '030', 'name' => 'SHEKEL (ISRAEL) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '031', 'name' => 'PESO BOLIVIANO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '032', 'name' => 'PESO COLOMBIANO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '033', 'name' => 'PESO CHILENO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '034', 'name' => 'RAND (SUDAFRICANO)', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '035', 'name' => 'NUEVO SOL PERUANO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '036', 'name' => 'SUCRE (ECUATORIANO) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '040', 'name' => 'LEI RUMANOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '041', 'name' => 'DERECHOS ESPECIALES DE GIRO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '042', 'name' => 'PESOS DOMINICANOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '043', 'name' => 'BALBOAS PANAMEÑAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '044', 'name' => 'CORDOBAS NICARAGÛENSES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '045', 'name' => 'DIRHAM MARROQUÍES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '046', 'name' => 'LIBRAS EGIPCIAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '047', 'name' => 'RIYALS SAUDITAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '048', 'name' => 'BRANCOS BELGAS FINANCIERAS', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '049', 'name' => 'GRAMOS DE ORO FINO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '050', 'name' => 'LIBRAS IRLANDESAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '051', 'name' => 'Dólar DE HONG KONG ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '052', 'name' => 'Dólar DE SINGAPUR ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '053', 'name' => 'Dólar DE JAMAICA ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '054', 'name' => 'Dólar DE TAIWAN ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '055', 'name' => 'QUETZAL (GUATEMALTECOS) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '056', 'name' => 'FORINT (HUNGRIA) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '057', 'name' => 'BAHT (TAILANDIA) ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '058', 'name' => 'ECU ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '059', 'name' => 'DINAR KUWAITI ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '060', 'name' => 'EURO ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '061', 'name' => 'ZLTYS POLACOS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '062', 'name' => 'RUPIAS HINDÚES ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '063', 'name' => 'LEMPIRAS HONDUREÑAS ', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '064', 'name' => 'YUAN (Rep. Pop. China)', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
        ['code_afip' => '', 'name' => 'BITCOIN', 'code_iso' => '', 'symbol' => '', 'quotation_usd' => ''],
    ],

    'responsibilities' => [
        ['code_afip' => '1', 'name' => 'IVA Responsable Inscripto', 'abbreviation' => 'RI'],
        ['code_afip' => '2', 'name' => 'IVA Responsable no Inscripto', 'abbreviation' => 'RN'],
        ['code_afip' => '3', 'name' => 'IVA no Responsable', 'abbreviation' => 'IN'],
        ['code_afip' => '4', 'name' => 'IVA Sujeto Exento', 'abbreviation' => 'IS'],
        ['code_afip' => '5', 'name' => 'Consumidor Final', 'abbreviation' => 'CF'],
        ['code_afip' => '6', 'name' => 'Responsable Monotributo', 'abbreviation' => 'MO'],
        ['code_afip' => '7', 'name' => 'Sujeto no Categorizado', 'abbreviation' => 'SC'],
        ['code_afip' => '8', 'name' => 'Proveedor del Exterior', 'abbreviation' => 'PE'],
        ['code_afip' => '9', 'name' => 'Cliente del Exterior', 'abbreviation' => 'CE'],
        ['code_afip' => '10', 'name' => 'IVA Liberado – Ley Nº 19.640', 'abbreviation' => 'IL'],
        ['code_afip' => '11', 'name' => 'IVA Responsable Inscripto – Agente de Percepción', 'abbreviation' => 'AP'],
        ['code_afip' => '12', 'name' => 'Pequeño Contribuyente Eventual', 'abbreviation' => 'PC'],
        ['code_afip' => '13', 'name' => 'Monotributista Social', 'abbreviation' => 'MS'],
        ['code_afip' => '14', 'name' => 'Pequeño Contribuyente Eventual Social', 'abbreviation' => 'PS'],
    ],

];